# Generated by Django 3.2 on 2022-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tags', models.TextField(db_column='tags', max_length=255, verbose_name='标签')),
            ],
            options={
                'verbose_name': '景点标签',
                'verbose_name_plural': '标签管理',
                'db_table': 'travel_tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpotInfo',
            fields=[
                ('poiId', models.IntegerField(primary_key=True, serialize=False)),
                ('poiName', models.CharField(db_column='poiName', default='', max_length=255, verbose_name='景点名')),
                ('price', models.FloatField()),
                ('coordinate', models.CharField(db_column='coordinate', default='', max_length=255, verbose_name='坐标')),
                ('priceTypeDesc', models.CharField(blank=True, db_column='priceTypeDesc', default='', max_length=255, null=True, verbose_name='是否免费')),
                ('shortFeatures', models.CharField(blank=True, db_column='shortFeatures', default='', max_length=255, null=True, verbose_name='景点短特征')),
                ('sightLevelStr', models.CharField(blank=True, db_column='sightLevelStr', default='', max_length=4, null=True, verbose_name='星级')),
                ('tagNameList', models.CharField(blank=True, db_column='tagNameList', default='', max_length=255, null=True, verbose_name='标签')),
                ('distanceStr', models.CharField(blank=True, db_column='distanceStr', default='', max_length=255, null=True, verbose_name='距离市区距离')),
                ('commentCount', models.IntegerField()),
                ('commentScore', models.FloatField()),
                ('heatScore', models.FloatField()),
                ('coverImageUrl', models.CharField(db_column='coverImageUrl', default='', max_length=255, null=True, verbose_name='图片链接')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点信息管理',
                'db_table': 'travel_spot',
                'managed': True,
            },
        ),
    ]
