# Generated by Django 3.2 on 2022-07-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotinfo',
            name='commentCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spotinfo',
            name='commentScore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='spotinfo',
            name='heatScore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='spotinfo',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterModelTable(
            name='spotinfo',
            table='poi11222',
        ),
    ]
