# Generated by Django 3.2 on 2022-07-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20220712_1528'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commenttag',
            table='tag111222',
        ),
        migrations.AlterModelTable(
            name='spotinfo',
            table='poi111222',
        ),
    ]
